### ISSUE TITLE
ARM机器无法运行

### ISSUE THREAD

**Issue by wang93wei** [sjlleo/TubeCheck#1]
报错
![image](https://user-images.githubusercontent.com/6371053/133382627-3987831d-c305-4d1f-ab6f-960502668589.png)

**Comment by fanmli** [comment]
一样，麻烦作者出个ARM版本！

**Comment by sjlleo** [comment]
Release已经有编译好的ARM版本，下载`tubecheck_1.0beta_linux_arm64`版本，然后运行即可
